dj_pd/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("performance/",include('products.urls',namespace="products"))
]
urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from .views import chart_select_view,add_purchase_view

app_name = 'products'

urlpatterns = [
    path("",chart_select_view,name="main-products-view"),
    path("add/",add_purchase_view,name="add-purchase-view")
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=220)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.name)
    

class Purchase(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    total_price = models.PositiveIntegerField(blank=True)
    salesman = models.ForeignKey(User,on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)

    def save(self,*args, **kwargs):
        self.total_price = self.price * self.quantity
        if not self.date:
            self.date = datetime.now()
        super(Purchase, self).save(*args, **kwargs)
        super().save(*args, **kwargs)
    
    # def saves(self, *args, **kwargs):
    #     if not self.date:
    #         self.date = datetime.now()
    #     super(Purchase, self).save(*args, **kwargs)
 
    def __str__(self) -> str:
        return "{} dona - {} maxsuloti {} so'mdan sotildi.Jami  summa {}.".format(self.quantity, self.product.name, self.price, self.total_price)

products/forms.py
from django import forms
from .models import Purchase,Product

class PurchaseForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all(),
                                     label='Product',
                                     widget=forms.Select(attrs={"class" : "ui selection dropdown field-with"}))
    class Meta:
        model = Purchase
        fields = ['product','price','quantity']

products/views.py
from django.shortcuts import render
from .models import Product,Purchase
import pandas as pd
from .utils import get_simple_plot
from .forms import PurchaseForm
# Create your views here.
def chart_select_view(request):
    error_message = None
    df = None
    graph = None
    price = None
    product_df = pd.DataFrame(Product.objects.all().values())
    purchase_df = pd.DataFrame(Purchase.objects.all().values())
    product_df["product_id"] = product_df["id"]
   
    
    if purchase_df.shape[0] > 0:
        df = pd.merge(product_df,purchase_df,on="product_id").drop(["id_y","date_y"],axis=1).rename({"id_x":"id","date_x":"date"},axis=1)
        price = df["price"]
        if request.method == "POST":
            chart_type = request.POST.get('sales')
            date_from = request.POST["date_from"]
            date_to = request.POST["date_to"]
            df["date"] = df["date"].apply(lambda x: x.strftime("%Y-%m-%d"))
            df2 = df.groupby("date",as_index=False)['total_price'].agg("sum")
            # print(df["date"])
            if chart_type != "":
                if date_from != "" and date_to != "":
                    df = df[(df['date']>date_from) & (df["date"]<date_to)]
                    df2 = df.groupby("date",as_index=False)['total_price'].agg("sum")
                    # print(df2)
                    # print(df)
                graph = get_simple_plot(chart_type, x=df2['date'],y=df2['total_price'],data=df)
            else:
                error_message = "Iltimos jadval turini aniq tanlang va sanalarni to'iq kiriting"

    else:
        error_message = "Databaseda malumot topilmadi"
        

    context = {
        # "products":product_df.to_html(),
        # "purchase":purchase_df.to_html(),
        # "df":df.to_html(),
        "graph":graph,
        "price":price,
        "error_message":error_message,
    }
    return render(request,"products/main.html",context)

def add_purchase_view(request):
    form = PurchaseForm(request.POST or None)
    added_message = None
    if form.is_valid():
        obj = form.save(commit=False)
        obj.salesman = request.user
        obj.save()

        form = PurchaseForm()
        added_message = "Savdo natijalari qo'shildi"

    context = {
        "form":form,
        "added_message":added_message,
    }
    return render(request,"products/add.html",context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!--Required metatags-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!--Jquery-->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <!--Custom css-->
        <link rel="stylesheet" type="text/css" href={% static "style.css" %}>
        <!--Semantic UI -->
        <link rel="stylesheet" type="text/css" href="https:/cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
        <script src="https:/cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

        <title> Analiz.uz {% block title %}{% endblock title %} </title>
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="ui container">
        {% block content %}
        {% endblock content %}
        </div>
        <script type="text/javascript" src={% static "main.js" %}></script>

    </body>
</html>

templates/navbar.html
{% url "products:main-products-view" as path_to_performance %}
{% url "products:add-purchase-view" as path_to_adding_records %}
<div class="ui secondary pointing menu">
    <a class="item">
      Asosiy oyna
    </a>
    <a href={{path_to_performance}} class="{% if request.path == path_to_performance %}active{% endif %} item">
      Hisobotlar
    </a>
    <a href={{path_to_adding_records}} class="item {% if request.path == path_to_adding_records %}active{% endif %}">
      Malumotlar kiritish
    </a>
    <div class="right menu">
      <a class="ui item">
        Chiqish
      </a>
    </div>
  </div>
  
  {% comment %} urlpatterns = [
    path("",chart_select_view,name="main-products-view"),
    path("add/",add_purchase_view,name="add-purchase-view")
] {% endcomment %}

templates/products/add.html
{% extends 'base.html' %}

{% block title %} add {% endblock title %}

{% block content %}
{% if added_message %}
    <div class="ui success message">
        <i class="close icon"></i>
            <div class="header">
            {{ added_message }}
            </div>
    </div>
  
{% endif %}

<form action="" method="POST" class = "ui form">
    {% csrf_token %}
    {{ form }}
    <button type="submit" class="ui positive button mtop"> Savdo natijalarini kiritish </button>
</form>
{% endblock content %}

templates/products/main.html
{% extends 'base.html' %}

{% block title %}  {% endblock title %}

{% block content %}

{% comment %} <div class="ui modal mymodal">
  <div class="header">Narxlar jadvali</div>
  <div class="ui container">
    <p>test1</p>
    <p>test2</p>
    <p>test3</p>
  </div>
</div> {% endcomment %}
<div>
    {% if error_message %}
    <div class="ui negative message">
      <i class="close icon"></i>
      <div class="header">
        {{ error_message }}
      </div>
    </div>
    {% endif %}

    {% if request.POST %}
      {% if graph %}
      <img src="data:image/png;base64, {{ graph | safe }}">
      {% endif %}
    {% endif %}
    {% comment %} <div>{{ price.mean | floatformat}}   o'rtacha narx</div>
    <br>
    {{ price.std | floatformat}} narxlarni o'rtacha siljishi
    <br>
    {{ price.median | floatformat}} o'rtacha narx
    <br>
    {{ price.min }} eng arzon sotuv
    <br>
    {{ price.max}} eng qimmat sotuv
    <br>
    {{ price.count }} kunlik savdolar soni {% endcomment %}
    <form action="" method="POST" class="ui form">
    {% csrf_token %}
        <div class="field">
            <label> O'zingizga maqul jadval turini tanlang: </label>
            <div class="ui selection dropdown">
                <input type="hidden" name="sales">
                <i class="dropdown icon"></i>
                <div class="default text">Jadval turini tanlang</div>
                    <div class="menu">
                        <div class="item" value="bar">Bar plot</div>
                        <div class="item" value="line">Line plot</div>
                        <div class="item" value="count">Count plot</div>
                    </div>
                
            </div>
        </div> 
        <div class="field">
            <div class="two fields">
              <div class="field"> 
                <label> Sanadan </label>
                <input type="date" name="date_from">
              </div>
              <div class="field">
                <label> Sanagacha </label>
                <input type="date" name="date_to">
              </div>
            </div>
          </div>
        <button class="ui primary button" type="submit">Tanlash</button>
    </form>
    {% comment %} <button class="ui secondary button" id="modal-btn">Natijani ko'rish</button> {% endcomment %}
    <a href={% url 'products:add-purchase-view' %}> <button class="ui positive button"> Savdo hisobotlarini kiritish </button></a>
</div>
{% endblock content %}